### PR TITLE
Added RandoBot to examples.

### PR DESCRIPTION
**Pull request by PhlexPlexico**
Also update README to give description of RandoBot, and added splash image.

### CODE REVIEW

**Comment by agermanidis** [comment]
No worries! This is impressive as your first foray into python. Just make sure that:

1) the bot behaves correctly when sent a snap
2) the bot behaves correctly when someone adds it to their friends
3) the bot behaves correctly when someone deletes it from their friends

**Comment by PhlexPlexico** [comment]
Okay! As for the indentation issues, with using vim it just seems it spaces too far compared to the other example files, but still seems to work? I mean, I run it off my Linux Server and it seems to go without issues! And as for the commented out parts; whenever the bot gets banned, you can login, write all the friends it currently has to a file. From this file, and upon logging into the new bot, it will re-add all the old users, so you don't have to tell people to re-add your new bot!

**Comment by N07070** [comment]
Up for a pull !

**Comment by Rob--** [comment]
Hey, @PhlexPlexico, that idea is pretty awesome - saving all friends and then readding them, etc... do you mind if I use it in my library?

**Comment by PhlexPlexico** [comment]
Hey @Rob-- ! It would be no problem at all! A bot I added got deleted and managed to do the same thing so I thought I could recreate it! Feel free to add it!

**Comment by Rob--** [comment]
@PhlexPlexico, thanks dude, what did the bot that got deleted do?

**Comment by PhlexPlexico** [comment]
It was actually using my randobot! What ended up happening though was a mass sweep of bot accounts from Snapchat. I had three emails come to me notifying that I must stop using third party applications or my account would be suspended! Happened to a local storifier bot here too!

**Comment by Rob--** [comment]
Ahh, I'm actually looking into a way to avoid being detected by sending analytics.

**Pull request merged**
