### PR TITLE
Capturesnaps

### PR DESCRIPTION
**Pull request by EthanBlackburn**

### CODE REVIEW

**Comment by EthanBlackburn** [comment]
Added ability to save snaps to current working directory and an accompanying example

**Comment by agermanidis** [comment]
Hey, I think it makes sense to keep get_snaps() as light as possible and not include additional functionality, but I'd love to add the CaptureBot example -- can you submit a pull request with just that instead? Thanks!

**Comment by EthanBlackburn** [comment]
If I remove the functionality from get_snaps() then the example won't work. Are you okay with that? I could make it read the snap.file inside the capturebot object, but that would be a hacky way to do it

**Comment by agermanidis** [comment]
I was thinking keeping the `save_snap` util function and then doing something like this for the Capture Bot:

```python
class CaptureBot(SnapchatBot):
     def on_snap(self, sender, snap):
         save_snap(sender, snap)
```

& modifying `save_snap` appropriately for that to work.

**Comment by EthanBlackburn** [comment]
Ahh, of course. Added another commit with all the functionality in save_snaps

**Comment by agermanidis** [comment]
Looks great, thanks!

**Comment by N07070** [comment]
This is awesome, thanks !

**Pull request merged**
